@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGZkOGUwMjNjOWQzNTU2MGM2MWYwYjMiLCJuYW1lIjoiRXhlY3V0b3IxIiwiZW1haWwiOiJFeGVjdXRvcjFAZXhlY3V0b3JzLmxvY2FsIiwicm9sZSI6IkV4ZWN1dG9yIiwiaWF0IjoxNjk0MzUzNTE0LCJleHAiOjE2OTQzNTQxMTR9.q0IKcOH2B71_RmvVXuRlZbIQfHepjWzGzHT5_jcUQfI
//64fe05f0a2bd2345642d7709

#Get Employer info
GET  http://localhost:3000/api/users/64fd8e503c9d35560c61f0b5 HTTP/1.1
Authorization: {{token}}
###

#Get Executor info
GET  http://localhost:3000/api/users/64fdda7b5da4da02acbf0361 HTTP/1.1
Authorization: {{token}}

###

#Update user info
Patch  http://localhost:3000/api/users/profile/edit HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
  "name": "update name2"
}
###


