@tokenExecutor = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjYzZWViNDUzOWZkZTZjMmVhZDJiMyIsIm5hbWUiOiJFeGVjdXRvcjQiLCJlbWFpbCI6IkV4ZWN1dG9yNEBleGVjdXRvcnMubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJpYXQiOjE2OTM4NTk1NzQsImV4cCI6MTY5Mzk0NTk3NH0.P-LrpIIbY_C3Q0UebrJ2AQT7ZIMrswcu2kkbewlXzx4
@tokenEmployer = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjY0ZTkwZmFlMmU4NTgzZGM2NGJjYiIsIm5hbWUiOiJFbXBsb3llcjQiLCJlbWFpbCI6IkVtcGxveWVyNEBleGVjdXRvcnMubG9jYWwiLCJyb2xlIjoiRW1wbG95ZXIiLCJpYXQiOjE2OTM4NjM1NzYsImV4cCI6MTY5Mzk0OTk3Nn0.bGXSsrDkG3d6xy90IHMNRryjqv0MQNPwoloRRUAkEVg
@tokenEmployer2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjY1ZTIwMzcyYWNhZjE4YTFmNDcyNiIsIm5hbWUiOiJFbXBsb3llcjUiLCJlbWFpbCI6IkVtcGxveWVyNUBleGVjdXRvcnMubG9jYWwiLCJyb2xlIjoiRW1wbG95ZXIiLCJpYXQiOjE2OTM4Njc1NjEsImV4cCI6MTY5Mzk1Mzk2MX0.0B3AflFYfIKf0ZGZrZyRw_FdkS8sLxaLvoQv5Mhk6pQ

#Get task by id
GET http://localhost:4000/api/tasks/5 HTTP/1.1
Authorization: {{tokenEmployer}}
###

#Create task
POST http://localhost:4000/api/tasks/create HTTP/1.1
Authorization: {{tokenEmployer}}
Content-Type: application/json

{
  "title": "Новое супер сложное задаааааниееее",
  "description": "Дочисталлллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллklklklklklklklklklkkkklklk",
  "categoryId": 3,
  "price": 2323.8999,
  "city": "Vladivostok",
  "employerId": "64e92572e629a8445238b337",
  "tags": ["tag1", "tag1", "tag1", "tag1", "tag1"]
}
###

#Update task
PATCH http://localhost:4000/api/tasks/27 HTTP/1.1
Authorization: {{tokenEmployer2}}
Content-Type: application/json

{
  "categoryId" : 4
}

###

#Delete Task
DELETE http://localhost:4000/api/tasks/17 HTTP/1.1
###


#Get User Tasks
GET http://localhost:4000/api/tasks/mytasks?userId=64ebc8ae9b9f8e5d31b778db HTTP/1.1

###


#Get Tasks
GET http://localhost:4000/api/tasks HTTP/1.1
Authorization: {{tokenExecutor}}

###

#Pin Task
POST http://localhost:4000/api/tasks/27/pin-task HTTP/1.1
Content-Type: application/json
Authorization: {{tokenEmployer}}

{
  "executorId": "64ebc8ae9b9f8e5d31b778db"
}

###


