@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0ZjVjZTdiMzI2NWQyZGZhYWIxZDVkMyIsIm5hbWUiOiJFeGVjdXRvcjQiLCJlbWFpbCI6IkV4ZWN1dG9yNEBleGVjdXRvcnMubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJpYXQiOjE2OTM4MzA3ODMsImV4cCI6MTY5MzgzMDc4M30.jts03wJFo1936SobIduZi7NJ_fhGAMQVpg48dTUY-pI

#Get task by id
GET http://localhost:4000/api/tasks/5 HTTP/1.1
Authorization: {{token}}
###

#Create task
POST http://localhost:4000/api/tasks/create HTTP/1.1
Content-Type: application/json

{
  "title": "Новое супер сложное задаааааниееее",
  "description": "Дочисталлллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллklklklklklklklklklkkkklklk",
  "categoryId": 3,
  "price": 2323.8999,
  "city": "Vladivostok",
  "employerId": "64e92572e629a8445238b337",
  "tags": ["tag1", "tag1", "tag1", "tag1", "tag1"]
}
###

#Update task
PATCH http://localhost:4000/api/tasks/6 HTTP/1.1
Content-Type: application/json

{
  "categoryId" : 3
}

###

#Delete Task
DELETE http://localhost:4000/api/tasks/17 HTTP/1.1
###


#Get User Tasks
GET http://localhost:4000/api/tasks/mytasks?userId=64ebc8ae9b9f8e5d31b778db HTTP/1.1

###


#Get Tasks
GET http://localhost:4000/api/tasks?tag=tag2&sortType=popular HTTP/1.1

###

#Pin Task
POST http://localhost:4000/api/tasks/22/pin-task HTTP/1.1
Content-Type: application/json

{
  "executorId": "64ebc8ae9b9f8e5d31b778db"
}

###


