@tokenExecutor = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGZkOGUwMjNjOWQzNTU2MGM2MWYwYjMiLCJuYW1lIjoiRXhlY3V0b3IxIiwiZW1haWwiOiJFeGVjdXRvcjFAZXhlY3V0b3JzLmxvY2FsIiwicm9sZSI6IkV4ZWN1dG9yIiwiaWF0IjoxNjk0MzM4NTgxLCJleHAiOjE2OTQzMzkxODF9.F3YbfkdWlpUhJZcxY8AmaOQP0lB65oeXWf1KU5lU4q4
@tokenEmployer = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGZkOGU1MDNjOWQzNTU2MGM2MWYwYjUiLCJuYW1lIjoiRW1wbG95ZXIxIiwiZW1haWwiOiJFbXBsb3llcjFAZXhlY3V0b3JzLmxvY2FsIiwicm9sZSI6IkVtcGxveWVyIiwiaWF0IjoxNjk0MzM4NjQ5LCJleHAiOjE2OTQzMzkyNDl9.PfIvP7IedXuTETrvf60FKRIuVfHciGn-JoHG_OfMVI4
@tokenEmployer2 = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGZkOGU3MTNjOWQzNTU2MGM2MWYwYjciLCJuYW1lIjoiRW1wbG95ZXIyIiwiZW1haWwiOiJFbXBsb3llcjJAZXhlY3V0b3JzLmxvY2FsIiwicm9sZSI6IkVtcGxveWVyIiwiaWF0IjoxNjk0MzM4Njc2LCJleHAiOjE2OTQzMzkyNzZ9.SMGxyoxFrDQnaOKD135B0Ka7QvAOO8ykxVMBT8lTupo

#Get task by id
GET http://localhost:4000/api/tasks/28 HTTP/1.1
Authorization: {{tokenEmployer}}
###

#Create task
POST http://localhost:4000/api/tasks/create HTTP/1.1
Authorization: {{tokenEmployer2}}
Content-Type: application/json

{
  "title": "Новое супер сложное задаааааниееее",
  "description": "Дочисталлллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллллklklklklklklklklklkkkklklk",
  "categoryId": 3,
  "price": 2323.8999,
  "city": "Vladivostok",
  "tags": ["tag1", "tag1", "tag1", "tag1", "tag1"]
}
###

#Update task
PATCH http://localhost:4000/api/tasks/27 HTTP/1.1
Authorization: {{tokenEmployer2}}
Content-Type: application/json

{
  "categoryId" : 4
}

###

#Delete Task
DELETE http://localhost:4000/api/tasks/17 HTTP/1.1
###


#Get User Tasks
GET http://localhost:4000/api/tasks/mytasks HTTP/1.1
Authorization: {{tokenEmployer}}
###


#Get Tasks
GET http://localhost:4000/api/tasks HTTP/1.1
Authorization: {{tokenExecutor}}

###

#Get User Tasks Count
GET http://localhost:4000/api/tasks/count HTTP/1.1
Authorization: {{tokenExecutor}}
Content-Type: application/json

{
  "userId": "64fd8e023c9d35560c61f0b3",
  "role": "Executor"
}


###





#Pin Task
POST http://localhost:4000/api/tasks/34/pin-task HTTP/1.1
Content-Type: application/json
Authorization: {{tokenEmployer2}}

{
  "executorId": "64fdda7b5da4da02acbf0361"
}

###


