# Create a new user
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Executor-sub7",
  "email": "Executor-sub7@executors.local",
  "birthDate": "2004-01-02",
  "password": "123456",
  "role": "Executor",
  "city": "Vladivostok"
}

###

#Auth user
POST http://localhost:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Employer5@executors.local",
  "password": "123456"
}

###
