@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGZhNTBjMDZlNjJlNGY5YTVhOTA4OTgiLCJ0b2tlbklkIjoiNjkwNzMxNmEtYzMwOS00ZDRiLTllZTItZWI4MjAxMjAyM2M2IiwiaWF0IjoxNjk0MjE1NzU0LCJleHAiOjE2OTY4MDc3NTR9.GVAbCfhXbIzmgevGKBHCVA0bVR5n6s2uskI28et5O30


# Create a new user
POST http://localhost:7007/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Executor3",
  "email": "Executor3@executors.local",
  "birthDate": "2004-01-02",
  "password": "123456",
  "role": "Executor",
  "city": "Vladivostok"
}

###

#Auth user
POST http://localhost:7007/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "Employer1@employers.local",
  "password": "123456"
}

###

# Get new JWT pair
POST http://localhost:7007/api/auth/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}
###


